(() => {
  const languageKey = "haller-language";
  const names = { it: "Italiano", en: "English", fr: "Francais", de: "Deutsch", es: "Espanol" };
  const text = {
    it: {},
    en: {
      "Torna alla home": "Back to home", "Home": "Home", "Contatti": "Contact", "Area clienti": "Customer area", "Accedi o registrati": "Sign in or register", "Accedi": "Sign in", "Registrati": "Register", "Esci": "Sign out", "Crea account": "Create account", "Account attivo": "Active account", "Accesso rapido": "Quick sign-in", "Continua con": "Continue with", "Checkout": "Checkout", "Pagamento alla consegna o crypto": "Cash on delivery or crypto", "Dati cliente": "Customer details", "Nome e cognome": "Full name", "Telefono": "Phone", "Indirizzo di consegna": "Delivery address", "Indirizzo": "Address", "Citta": "City", "Codice sconto": "Discount code", "Inserisci codice": "Enter code", "Applica sconto": "Apply discount", "Pagamento": "Payment", "Contrassegno": "Cash on delivery", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "You can pay the courier directly when your parcel arrives.", "Codice ordine": "Order code", "Copia": "Copy", "Copia indirizzo": "Copy address", "Tracciamento pagamento": "Payment tracking", "TX hash pagamento": "Payment TX hash", "Copia dati pagamento": "Copy payment details", "Conferma ordine": "Confirm order", "Riepilogo": "Summary", "Prodotto": "Product", "Metodo di pagamento": "Payment method", "Consegna": "Delivery", "Continua lo shopping": "Continue shopping", "Pannello riservato": "Restricted area", "Dashboard admin": "Admin dashboard", "Password admin": "Admin password", "Entra": "Sign in", "Aggiorna": "Refresh", "Metriche": "Metrics", "Ordini": "Orders", "Prodotti": "Products", "Utenti": "Users", "Video": "Video", "Attivita": "Activity", "Visite live": "Live visits", "Pagamenti": "Payments", "Tutti i diritti riservati.": "All rights reserved."
    },
    fr: {
      "Torna alla home": "Retour a l'accueil", "Home": "Accueil", "Contatti": "Contact", "Area clienti": "Espace client", "Accedi o registrati": "Connexion ou inscription", "Accedi": "Se connecter", "Registrati": "S'inscrire", "Esci": "Se deconnecter", "Crea account": "Creer un compte", "Account attivo": "Compte actif", "Accesso rapido": "Connexion rapide", "Continua con": "Continuer avec", "Checkout": "Paiement", "Pagamento alla consegna o crypto": "Paiement a la livraison ou crypto", "Dati cliente": "Informations client", "Nome e cognome": "Nom complet", "Telefono": "Telephone", "Indirizzo di consegna": "Adresse de livraison", "Indirizzo": "Adresse", "Citta": "Ville", "Codice sconto": "Code promotionnel", "Inserisci codice": "Saisir le code", "Applica sconto": "Appliquer", "Pagamento": "Paiement", "Contrassegno": "Paiement a la livraison", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "Payez directement le transporteur a la reception du colis.", "Codice ordine": "Numero de commande", "Copia": "Copier", "Copia indirizzo": "Copier l'adresse", "Tracciamento pagamento": "Suivi du paiement", "TX hash pagamento": "TX hash du paiement", "Copia dati pagamento": "Copier les donnees", "Conferma ordine": "Confirmer la commande", "Riepilogo": "Recapitulatif", "Prodotto": "Produit", "Metodo di pagamento": "Moyen de paiement", "Consegna": "Livraison", "Continua lo shopping": "Continuer vos achats", "Pannello riservato": "Espace reserve", "Dashboard admin": "Tableau de bord admin", "Password admin": "Mot de passe admin", "Entra": "Se connecter", "Aggiorna": "Actualiser", "Metriche": "Indicateurs", "Ordini": "Commandes", "Prodotti": "Produits", "Utenti": "Utilisateurs", "Video": "Videos", "Attivita": "Activite", "Visite live": "Visites en direct", "Pagamenti": "Paiements", "Tutti i diritti riservati.": "Tous droits reserves."
    },
    de: {
      "Torna alla home": "Zuruck zur Startseite", "Home": "Startseite", "Contatti": "Kontakt", "Area clienti": "Kundenbereich", "Accedi o registrati": "Anmelden oder registrieren", "Accedi": "Anmelden", "Registrati": "Registrieren", "Esci": "Abmelden", "Crea account": "Konto erstellen", "Account attivo": "Aktives Konto", "Accesso rapido": "Schnell anmelden", "Continua con": "Weiter mit", "Checkout": "Kasse", "Pagamento alla consegna o crypto": "Nachnahme oder Krypto", "Dati cliente": "Kundendaten", "Nome e cognome": "Vollstandiger Name", "Telefono": "Telefon", "Indirizzo di consegna": "Lieferadresse", "Indirizzo": "Adresse", "Citta": "Stadt", "Codice sconto": "Rabattcode", "Inserisci codice": "Code eingeben", "Applica sconto": "Rabatt anwenden", "Pagamento": "Zahlung", "Contrassegno": "Nachnahme", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "Sie zahlen direkt beim Zusteller, wenn das Paket ankommt.", "Codice ordine": "Bestellnummer", "Copia": "Kopieren", "Copia indirizzo": "Adresse kopieren", "Tracciamento pagamento": "Zahlungsverfolgung", "TX hash pagamento": "Zahlungs-TX-Hash", "Copia dati pagamento": "Zahlungsdaten kopieren", "Conferma ordine": "Bestellung bestatigen", "Riepilogo": "Zusammenfassung", "Prodotto": "Produkt", "Metodo di pagamento": "Zahlungsart", "Consegna": "Lieferung", "Continua lo shopping": "Weiter einkaufen", "Pannello riservato": "Geschutzter Bereich", "Dashboard admin": "Admin-Dashboard", "Password admin": "Admin-Passwort", "Entra": "Anmelden", "Aggiorna": "Aktualisieren", "Metriche": "Kennzahlen", "Ordini": "Bestellungen", "Prodotti": "Produkte", "Utenti": "Nutzer", "Video": "Videos", "Attivita": "Aktivitat", "Visite live": "Live-Besuche", "Pagamenti": "Zahlungen", "Tutti i diritti riservati.": "Alle Rechte vorbehalten."
    },
    es: {
      "Torna alla home": "Volver al inicio", "Home": "Inicio", "Contatti": "Contacto", "Area clienti": "Area de clientes", "Accedi o registrati": "Inicia sesion o registrate", "Accedi": "Iniciar sesion", "Registrati": "Registrarse", "Esci": "Cerrar sesion", "Crea account": "Crear cuenta", "Account attivo": "Cuenta activa", "Accesso rapido": "Acceso rapido", "Continua con": "Continuar con", "Checkout": "Pago", "Pagamento alla consegna o crypto": "Pago contra reembolso o cripto", "Dati cliente": "Datos del cliente", "Nome e cognome": "Nombre completo", "Telefono": "Telefono", "Indirizzo di consegna": "Direccion de entrega", "Indirizzo": "Direccion", "Citta": "Ciudad", "Codice sconto": "Codigo de descuento", "Inserisci codice": "Introduce el codigo", "Applica sconto": "Aplicar descuento", "Pagamento": "Pago", "Contrassegno": "Contra reembolso", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "Puedes pagar directamente al mensajero al recibir el paquete.", "Codice ordine": "Codigo de pedido", "Copia": "Copiar", "Copia indirizzo": "Copiar direccion", "Tracciamento pagamento": "Seguimiento del pago", "TX hash pagamento": "TX hash del pago", "Copia dati pagamento": "Copiar datos de pago", "Conferma ordine": "Confirmar pedido", "Riepilogo": "Resumen", "Prodotto": "Producto", "Metodo di pagamento": "Metodo de pago", "Consegna": "Entrega", "Continua lo shopping": "Seguir comprando", "Pannello riservato": "Area restringida", "Dashboard admin": "Panel de administracion", "Password admin": "Contrasena admin", "Entra": "Entrar", "Aggiorna": "Actualizar", "Metriche": "Metricas", "Ordini": "Pedidos", "Prodotti": "Productos", "Utenti": "Usuarios", "Video": "Videos", "Attivita": "Actividad", "Visite live": "Visitas en directo", "Pagamenti": "Pagos", "Tutti i diritti riservati.": "Todos los derechos reservados."
    }
  };
  const originals = new WeakMap();
  const legalOriginals = new WeakMap();
  const legalPages = {
    en: {
      terms: `<p class="legal-eyebrow">Legal information</p><h1>Terms and conditions</h1><p>Last updated: 14 July 2026. These terms govern purchases made through Haller Boutique.</p><section class="legal-section"><h2>Orders and availability</h2><p>Submitting an order is a purchase offer. Order confirmation and shipping updates are sent to the contact details provided by the customer. Product availability is checked before fulfilment.</p></section><section class="legal-section"><h2>Prices and payments</h2><p>Prices and available payment methods are shown at checkout before the order is submitted. For cryptocurrency payments, use only the instructions and order code displayed during purchase.</p></section><section class="legal-section"><h2>Shipping and delivery</h2><p>Shipping information is available on the <a href="spedizioni.html">Shipping</a> page. The customer must verify the address entered at checkout and monitor the delivery status.</p></section><section class="legal-section"><h2>Replacements, withdrawal and refunds</h2><p>For after-sales support, Haller Boutique gives priority to replacing goods after checking the case and product availability. If goods are damaged, non-conforming or lost in transit, contact Aurora promptly with photos and the order code.</p><p>Refunds are assessed for these exceptional cases and where required by applicable law. This policy does not limit the 14-day right of withdrawal or statutory conformity guarantee where applicable.</p></section><section class="legal-section"><h2>Support</h2><p>For orders, replacements, deliveries and reports: <a href="index.html?chat=1">open Aurora chat</a>.</p></section>`,
      shipping: `<p class="legal-eyebrow">Purchase information</p><h1>Shipping</h1><p>Track your order using the code received in the purchase confirmation. For delivery support, always provide your order code.</p><section class="legal-section"><h2>Order preparation</h2><p>Orders are prepared after purchase details and product availability are checked. Support may contact the customer before shipping when information is incomplete.</p></section><section class="legal-section"><h2>Address and delivery</h2><p>The customer must provide a complete and accurate address. At delivery, check the external condition of the parcel before accepting it and report any issue promptly.</p></section><section class="legal-section"><h2>Lost or damaged order</h2><p>If a parcel is damaged or not delivered, contact Aurora with the order code, parcel photos and a short description. After verification, Haller Boutique prioritises replacement, without affecting rights under applicable law.</p></section><section class="legal-section"><h2>Shipping support</h2><p><a href="index.html?chat=1">Open Aurora chat</a></p></section>`,
      privacy: `<p class="legal-eyebrow">Personal data</p><h1>Privacy Policy</h1><p>Last updated: 14 July 2026. This notice describes the processing of personal data collected through Haller Boutique.</p><section class="legal-section"><h2>Data and purposes</h2><p>We may process identity, contact and delivery data, order information, support communications and technical browsing data to manage orders, shipping, customer support, security, abuse prevention and legal obligations.</p></section><section class="legal-section"><h2>Legal basis and retention</h2><p>Processing is necessary to perform a contract, meet legal duties and, where needed, for the legitimate interest in security and correct service operation. Data is retained only as long as necessary for these purposes and legal obligations.</p></section><section class="legal-section"><h2>Try-on photos</h2><p>Only when the user expressly authorises it, the uploaded photo and try-on preview are kept in a private archive accessible solely by store administration for support and recovery. Images are automatically deleted after 30 days.</p></section><section class="legal-section"><h2>Recipients and rights</h2><p>Data may be handled by providers supporting hosting, shipping, assistance, payments and security. We do not sell personal data. Where applicable, you may request access, correction, deletion, restriction, portability or object to processing.</p></section><section class="legal-section"><h2>Privacy contacts</h2><p>For requests about orders or personal data, contact <a href="index.html?chat=1">Aurora, Haller Boutique online assistant</a>.</p></section>`
    },
    fr: {
      terms: `<p class="legal-eyebrow">Informations legales</p><h1>Conditions generales</h1><p>Derniere mise a jour : 14 juillet 2026. Ces conditions regissent les achats effectues sur Haller Boutique.</p><section class="legal-section"><h2>Commandes et disponibilite</h2><p>L'envoi d'une commande constitue une proposition d'achat. La confirmation et les informations d'expedition sont envoyees aux coordonnees du client. La disponibilite est verifiee avant traitement.</p></section><section class="legal-section"><h2>Prix et paiements</h2><p>Les prix et moyens de paiement disponibles sont indiques au paiement. Pour les cryptomonnaies, utilisez uniquement les instructions et le numero de commande affiches.</p></section><section class="legal-section"><h2>Livraison, remplacement et remboursement</h2><p>Haller Boutique privilegie le remplacement apres verification. En cas de produit endommage, non conforme ou perdu, contactez rapidement Aurora avec photos et numero de commande. Les remboursements sont evalues dans ces cas exceptionnels et selon la loi applicable.</p></section><section class="legal-section"><h2>Assistance</h2><p><a href="index.html?chat=1">Ouvrir le chat Aurora</a></p></section>`,
      shipping: `<p class="legal-eyebrow">Informations achat</p><h1>Livraison</h1><p>Suivez la commande avec le code recu dans la confirmation. Pour toute assistance, indiquez toujours ce code.</p><section class="legal-section"><h2>Preparation</h2><p>Les commandes sont preparees apres verification des donnees et de la disponibilite. L'assistance peut contacter le client avant expedition en cas d'information incomplete.</p></section><section class="legal-section"><h2>Adresse et livraison</h2><p>Le client doit fournir une adresse complete et correcte. Verifiez l'etat exterieur du colis avant de l'accepter et signalez rapidement toute anomalie.</p></section><section class="legal-section"><h2>Colis perdu ou endommage</h2><p>Contactez Aurora avec le code commande, des photos et une breve description. Apres verification, Haller Boutique privilegie le remplacement, sans prejudice des droits legaux.</p></section>`,
      privacy: `<p class="legal-eyebrow">Donnees personnelles</p><h1>Politique de confidentialite</h1><p>Derniere mise a jour : 14 juillet 2026. Cette notice decrit le traitement des donnees collectees par Haller Boutique.</p><section class="legal-section"><h2>Donnees et finalites</h2><p>Nous pouvons traiter les donnees d'identite, de contact, de livraison, de commande, d'assistance et de navigation pour les commandes, livraisons, securite et obligations legales.</p></section><section class="legal-section"><h2>Base juridique et conservation</h2><p>Le traitement est necessaire au contrat, aux obligations legales et a la securite du service. Les donnees sont conservees pendant la duree necessaire.</p></section><section class="legal-section"><h2>Photos try-on</h2><p>Uniquement avec l'autorisation expresse de l'utilisateur, la photo et l'aperçu try-on sont conserves dans une archive privee accessible a l'administration pendant 30 jours maximum.</p></section><section class="legal-section"><h2>Contacts</h2><p>Pour les demandes relatives aux commandes ou aux donnees : <a href="index.html?chat=1">Aurora</a>.</p></section>`
    },
    de: {
      terms: `<p class="legal-eyebrow">Rechtliche Informationen</p><h1>Allgemeine Geschaftsbedingungen</h1><p>Letzte Aktualisierung: 14. Juli 2026. Diese Bedingungen gelten fur Einkaufe bei Haller Boutique.</p><section class="legal-section"><h2>Bestellungen und Verfugbarkeit</h2><p>Die Bestellung ist ein Kaufangebot. Bestatigung und Versandinformationen werden an die Kundendaten gesendet. Die Verfugbarkeit wird vor der Bearbeitung gepruft.</p></section><section class="legal-section"><h2>Preise und Zahlungen</h2><p>Preise und Zahlungsarten werden an der Kasse angezeigt. Fur Kryptowahrungen sind ausschliesslich die angezeigten Anweisungen und Bestellnummer zu verwenden.</p></section><section class="legal-section"><h2>Lieferung, Ersatz und Erstattung</h2><p>Haller Boutique bevorzugt nach Prufung einen Warenersatz. Bei beschadigter, nicht konformer oder verlorener Ware kontaktieren Sie Aurora mit Fotos und Bestellnummer. Erstattungen werden in Ausnahmefallen und nach geltendem Recht gepruft.</p></section><section class="legal-section"><h2>Support</h2><p><a href="index.html?chat=1">Aurora-Chat offnen</a></p></section>`,
      shipping: `<p class="legal-eyebrow">Kaufinformationen</p><h1>Versand</h1><p>Verfolgen Sie Ihre Bestellung mit dem Code aus der Kaufbestatigung. Geben Sie diesen Code bei Supportanfragen immer an.</p><section class="legal-section"><h2>Bestellvorbereitung</h2><p>Bestellungen werden nach Prufung der Angaben und Verfugbarkeit vorbereitet. Bei unvollstandigen Angaben kann der Support vor dem Versand Kontakt aufnehmen.</p></section><section class="legal-section"><h2>Adresse und Zustellung</h2><p>Der Kunde muss eine vollstandige korrekte Adresse angeben. Prufen Sie das Paket vor Annahme und melden Sie Auffalligkeiten umgehend.</p></section><section class="legal-section"><h2>Verlorenes oder beschadigtes Paket</h2><p>Kontaktieren Sie Aurora mit Bestellnummer, Fotos und kurzer Beschreibung. Nach Prufung wird ein Ersatz bevorzugt, unbeschadet gesetzlicher Rechte.</p></section>`,
      privacy: `<p class="legal-eyebrow">Personliche Daten</p><h1>Datenschutzerklarung</h1><p>Letzte Aktualisierung: 14. Juli 2026. Diese Information beschreibt die Verarbeitung personenbezogener Daten bei Haller Boutique.</p><section class="legal-section"><h2>Daten und Zwecke</h2><p>Wir konnen Identitats-, Kontakt-, Liefer-, Bestell-, Support- und technische Browsingdaten fur Bestellungen, Lieferungen, Sicherheit und gesetzliche Pflichten verarbeiten.</p></section><section class="legal-section"><h2>Rechtsgrundlage und Speicherung</h2><p>Die Verarbeitung dient Vertrag, gesetzlichen Pflichten und der Sicherheit des Dienstes. Daten werden nur so lange wie erforderlich gespeichert.</p></section><section class="legal-section"><h2>Try-on-Fotos</h2><p>Nur mit ausdrucklicher Zustimmung werden Foto und Vorschau bis zu 30 Tage in einem privaten Archiv der Shopverwaltung gespeichert.</p></section><section class="legal-section"><h2>Kontakt</h2><p>Bei Fragen zu Bestellungen oder Daten: <a href="index.html?chat=1">Aurora</a>.</p></section>`
    },
    es: {
      terms: `<p class="legal-eyebrow">Informacion legal</p><h1>Terminos y condiciones</h1><p>Ultima actualizacion: 14 de julio de 2026. Estas condiciones regulan las compras en Haller Boutique.</p><section class="legal-section"><h2>Pedidos y disponibilidad</h2><p>El envio de un pedido constituye una propuesta de compra. La confirmacion y la informacion de envio se envian a los datos del cliente. La disponibilidad se comprueba antes de la preparacion.</p></section><section class="legal-section"><h2>Precios y pagos</h2><p>Los precios y metodos de pago disponibles aparecen en el pago. Para criptomonedas usa solo las instrucciones y el codigo de pedido mostrados.</p></section><section class="legal-section"><h2>Entrega, sustitucion y reembolso</h2><p>Haller Boutique prioriza la sustitucion tras verificar el caso. Si la mercancia llega danada, no es conforme o se pierde, contacta pronto con Aurora con fotos y codigo de pedido. Los reembolsos se valoran en casos excepcionales y conforme a la ley.</p></section><section class="legal-section"><h2>Asistencia</h2><p><a href="index.html?chat=1">Abrir el chat Aurora</a></p></section>`,
      shipping: `<p class="legal-eyebrow">Informacion de compra</p><h1>Envios</h1><p>Sigue tu pedido con el codigo recibido en la confirmacion. Para asistencia de entrega indica siempre ese codigo.</p><section class="legal-section"><h2>Preparacion</h2><p>Los pedidos se preparan tras verificar datos y disponibilidad. El soporte puede contactar al cliente antes del envio si falta informacion.</p></section><section class="legal-section"><h2>Direccion y entrega</h2><p>El cliente debe indicar una direccion completa y correcta. Comprueba el estado exterior del paquete antes de aceptarlo e informa pronto de cualquier incidencia.</p></section><section class="legal-section"><h2>Pedido perdido o danado</h2><p>Contacta con Aurora con el codigo de pedido, fotos y una breve descripcion. Tras la verificacion, se prioriza la sustitucion sin limitar los derechos legales.</p></section>`,
      privacy: `<p class="legal-eyebrow">Datos personales</p><h1>Politica de privacidad</h1><p>Ultima actualizacion: 14 de julio de 2026. Esta informacion describe el tratamiento de datos personales en Haller Boutique.</p><section class="legal-section"><h2>Datos y finalidades</h2><p>Podemos tratar datos de identidad, contacto, entrega, pedidos, asistencia y navegacion para gestionar pedidos, envios, seguridad y obligaciones legales.</p></section><section class="legal-section"><h2>Base legal y conservacion</h2><p>El tratamiento es necesario para el contrato, obligaciones legales y seguridad del servicio. Los datos se conservan solo el tiempo necesario.</p></section><section class="legal-section"><h2>Fotos try-on</h2><p>Solo con autorizacion expresa se conservan la foto y vista previa durante un maximo de 30 dias en un archivo privado de administracion.</p></section><section class="legal-section"><h2>Contacto</h2><p>Para pedidos o datos personales: <a href="index.html?chat=1">Aurora</a>.</p></section>`
    }
  };
  const language = () => localStorage.getItem(languageKey) || "it";
  const translate = (value) => text[language()]?.[value] || value;
  const apply = () => {
    document.documentElement.lang = language();
    const legalPage = document.querySelector("[data-legal-page]");
    if (legalPage) {
      if (!legalOriginals.has(legalPage)) legalOriginals.set(legalPage, legalPage.innerHTML);
      legalPage.innerHTML = language() === "it"
        ? legalOriginals.get(legalPage)
        : legalPages[language()]?.[legalPage.dataset.legalPage] || legalOriginals.get(legalPage);
    }
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (!node.parentElement || ["SCRIPT", "STYLE"].includes(node.parentElement.tagName)) continue;
      const original = originals.get(node) ?? node.nodeValue;
      originals.set(node, original);
      const trimmed = original.trim();
      if (!trimmed) continue;
      const value = translate(trimmed);
      node.nodeValue = value === trimmed ? original : original.replace(trimmed, value);
    }
    document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
      element.placeholder = translate(element.dataset.i18nPlaceholder);
    });
  };
  const bindPicker = (picker) => {
    const toggle = picker.querySelector(".language-toggle");
    const menu = picker.querySelector(".language-menu");
    const options = picker.querySelectorAll("[data-language-option]");
    if (!toggle || !menu) return;
    const refresh = () => {
      const current = language();
      options.forEach((option) => option.setAttribute("aria-checked", String(option.dataset.languageOption === current)));
      toggle.setAttribute("aria-label", `Change language: ${names[current]}`);
    };
    refresh();
    toggle.addEventListener("click", () => {
      const open = menu.classList.toggle("is-open");
      toggle.setAttribute("aria-expanded", String(open));
    });
    options.forEach((option) => option.addEventListener("click", () => {
      localStorage.setItem(languageKey, option.dataset.languageOption);
      refresh();
      apply();
      window.dispatchEvent(new CustomEvent("haller-language-change", { detail: option.dataset.languageOption }));
      menu.classList.remove("is-open");
      toggle.setAttribute("aria-expanded", "false");
    }));
  };
  window.HallerI18n = { apply, translate, language };
  document.addEventListener("DOMContentLoaded", () => {
    apply();
    document.querySelectorAll("[data-language-picker]").forEach(bindPicker);
  });
  window.addEventListener("haller-language-change", apply);
})();
