(() => {
  const languageKey = "haller-language";
  const names = { it: "Italiano", en: "English", fr: "Francais", de: "Deutsch", es: "Espanol" };
  const text = {
    it: {},
    en: {
      "Torna alla home": "Back to home", "Home": "Home", "Contatti": "Contact", "Area clienti": "Customer area", "Accedi o registrati": "Sign in or register", "Accedi": "Sign in", "Registrati": "Register", "Esci": "Sign out", "Crea account": "Create account", "Account attivo": "Active account", "Accesso rapido": "Quick sign-in", "Continua con": "Continue with", "Checkout": "Checkout", "Pagamento alla consegna o crypto": "Cash on delivery or crypto", "Dati cliente": "Customer details", "Nome e cognome": "Full name", "Telefono": "Phone", "Indirizzo di consegna": "Delivery address", "Indirizzo": "Address", "Citta": "City", "Codice sconto": "Discount code", "Inserisci codice": "Enter code", "Applica sconto": "Apply discount", "Pagamento": "Payment", "Contrassegno": "Cash on delivery", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "You can pay the courier directly when your parcel arrives.", "Codice ordine": "Order code", "Copia": "Copy", "Copia indirizzo": "Copy address", "Tracciamento pagamento": "Payment tracking", "TX hash pagamento": "Payment TX hash", "Copia dati pagamento": "Copy payment details", "Conferma ordine": "Confirm order", "Riepilogo": "Summary", "Prodotto": "Product", "Metodo di pagamento": "Payment method", "Consegna": "Delivery", "Continua lo shopping": "Continue shopping", "Pannello riservato": "Restricted area", "Dashboard admin": "Admin dashboard", "Password admin": "Admin password", "Entra": "Sign in", "Aggiorna": "Refresh", "Metriche": "Metrics", "Ordini": "Orders", "Prodotti": "Products", "Utenti": "Users", "Video": "Video", "Attivita": "Activity", "Visite live": "Live visits", "Pagamenti": "Payments", "Tutti i diritti riservati.": "All rights reserved."
    },
    fr: {
      "Torna alla home": "Retour a l'accueil", "Home": "Accueil", "Contatti": "Contact", "Area clienti": "Espace client", "Accedi o registrati": "Connexion ou inscription", "Accedi": "Se connecter", "Registrati": "S'inscrire", "Esci": "Se deconnecter", "Crea account": "Creer un compte", "Account attivo": "Compte actif", "Accesso rapido": "Connexion rapide", "Continua con": "Continuer avec", "Checkout": "Paiement", "Pagamento alla consegna o crypto": "Paiement a la livraison ou crypto", "Dati cliente": "Informations client", "Nome e cognome": "Nom complet", "Telefono": "Telephone", "Indirizzo di consegna": "Adresse de livraison", "Indirizzo": "Adresse", "Citta": "Ville", "Codice sconto": "Code promotionnel", "Inserisci codice": "Saisir le code", "Applica sconto": "Appliquer", "Pagamento": "Paiement", "Contrassegno": "Paiement a la livraison", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "Payez directement le transporteur a la reception du colis.", "Codice ordine": "Numero de commande", "Copia": "Copier", "Copia indirizzo": "Copier l'adresse", "Tracciamento pagamento": "Suivi du paiement", "TX hash pagamento": "TX hash du paiement", "Copia dati pagamento": "Copier les donnees", "Conferma ordine": "Confirmer la commande", "Riepilogo": "Recapitulatif", "Prodotto": "Produit", "Metodo di pagamento": "Moyen de paiement", "Consegna": "Livraison", "Continua lo shopping": "Continuer vos achats", "Pannello riservato": "Espace reserve", "Dashboard admin": "Tableau de bord admin", "Password admin": "Mot de passe admin", "Entra": "Se connecter", "Aggiorna": "Actualiser", "Metriche": "Indicateurs", "Ordini": "Commandes", "Prodotti": "Produits", "Utenti": "Utilisateurs", "Video": "Videos", "Attivita": "Activite", "Visite live": "Visites en direct", "Pagamenti": "Paiements", "Tutti i diritti riservati.": "Tous droits reserves."
    },
    de: {
      "Torna alla home": "Zuruck zur Startseite", "Home": "Startseite", "Contatti": "Kontakt", "Area clienti": "Kundenbereich", "Accedi o registrati": "Anmelden oder registrieren", "Accedi": "Anmelden", "Registrati": "Registrieren", "Esci": "Abmelden", "Crea account": "Konto erstellen", "Account attivo": "Aktives Konto", "Accesso rapido": "Schnell anmelden", "Continua con": "Weiter mit", "Checkout": "Kasse", "Pagamento alla consegna o crypto": "Nachnahme oder Krypto", "Dati cliente": "Kundendaten", "Nome e cognome": "Vollstandiger Name", "Telefono": "Telefon", "Indirizzo di consegna": "Lieferadresse", "Indirizzo": "Adresse", "Citta": "Stadt", "Codice sconto": "Rabattcode", "Inserisci codice": "Code eingeben", "Applica sconto": "Rabatt anwenden", "Pagamento": "Zahlung", "Contrassegno": "Nachnahme", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "Sie zahlen direkt beim Zusteller, wenn das Paket ankommt.", "Codice ordine": "Bestellnummer", "Copia": "Kopieren", "Copia indirizzo": "Adresse kopieren", "Tracciamento pagamento": "Zahlungsverfolgung", "TX hash pagamento": "Zahlungs-TX-Hash", "Copia dati pagamento": "Zahlungsdaten kopieren", "Conferma ordine": "Bestellung bestatigen", "Riepilogo": "Zusammenfassung", "Prodotto": "Produkt", "Metodo di pagamento": "Zahlungsart", "Consegna": "Lieferung", "Continua lo shopping": "Weiter einkaufen", "Pannello riservato": "Geschutzter Bereich", "Dashboard admin": "Admin-Dashboard", "Password admin": "Admin-Passwort", "Entra": "Anmelden", "Aggiorna": "Aktualisieren", "Metriche": "Kennzahlen", "Ordini": "Bestellungen", "Prodotti": "Produkte", "Utenti": "Nutzer", "Video": "Videos", "Attivita": "Aktivitat", "Visite live": "Live-Besuche", "Pagamenti": "Zahlungen", "Tutti i diritti riservati.": "Alle Rechte vorbehalten."
    },
    es: {
      "Torna alla home": "Volver al inicio", "Home": "Inicio", "Contatti": "Contacto", "Area clienti": "Area de clientes", "Accedi o registrati": "Inicia sesion o registrate", "Accedi": "Iniciar sesion", "Registrati": "Registrarse", "Esci": "Cerrar sesion", "Crea account": "Crear cuenta", "Account attivo": "Cuenta activa", "Accesso rapido": "Acceso rapido", "Continua con": "Continuar con", "Checkout": "Pago", "Pagamento alla consegna o crypto": "Pago contra reembolso o cripto", "Dati cliente": "Datos del cliente", "Nome e cognome": "Nombre completo", "Telefono": "Telefono", "Indirizzo di consegna": "Direccion de entrega", "Indirizzo": "Direccion", "Citta": "Ciudad", "Codice sconto": "Codigo de descuento", "Inserisci codice": "Introduce el codigo", "Applica sconto": "Aplicar descuento", "Pagamento": "Pago", "Contrassegno": "Contra reembolso", "Puoi pagare direttamente al corriere quando ricevi il pacco.": "Puedes pagar directamente al mensajero al recibir el paquete.", "Codice ordine": "Codigo de pedido", "Copia": "Copiar", "Copia indirizzo": "Copiar direccion", "Tracciamento pagamento": "Seguimiento del pago", "TX hash pagamento": "TX hash del pago", "Copia dati pagamento": "Copiar datos de pago", "Conferma ordine": "Confirmar pedido", "Riepilogo": "Resumen", "Prodotto": "Producto", "Metodo di pagamento": "Metodo de pago", "Consegna": "Entrega", "Continua lo shopping": "Seguir comprando", "Pannello riservato": "Area restringida", "Dashboard admin": "Panel de administracion", "Password admin": "Contrasena admin", "Entra": "Entrar", "Aggiorna": "Actualizar", "Metriche": "Metricas", "Ordini": "Pedidos", "Prodotti": "Productos", "Utenti": "Usuarios", "Video": "Videos", "Attivita": "Actividad", "Visite live": "Visitas en directo", "Pagamenti": "Pagos", "Tutti i diritti riservati.": "Todos los derechos reservados."
    }
  };
  const extraText = {
    en: {
      "Account | Haller Boutique": "Account | Haller Boutique", "Account - Haller Boutique": "Account - Haller Boutique", "Checkout | Haller Boutique": "Checkout | Haller Boutique", "Checkout - Haller Boutique": "Checkout - Haller Boutique", "Spedizioni | Haller Boutique": "Shipping | Haller Boutique", "Termini e condizioni | Haller Boutique": "Terms and conditions | Haller Boutique", "Privacy Policy | Haller Boutique": "Privacy Policy | Haller Boutique", "Admin | Haller Boutique": "Admin | Haller Boutique",
      "Tutti i diritti riservati.": "All rights reserved.", "Operazione in corso...": "Working...", "Operazione non riuscita.": "Operation failed.", "Account creato.": "Account created.", "Accesso effettuato.": "Signed in.", "Cliente": "Customer", "Cellulare non inserito": "Phone number not provided",
      "Cambia lingua": "Change language", "Menu account": "Account menu", "Accesso e registrazione": "Sign-in and registration", "Minimo 8 caratteri": "At least 8 characters", "© 2017 Haller Boutique. Tutti i diritti riservati.": "© 2017 Haller Boutique. All rights reserved.",
      "Menu checkout": "Checkout menu", "Checkout ordine": "Order checkout", "Città": "City", "Scegli metodo di pagamento": "Choose a payment method", "Riepilogo ordine": "Order summary", "Il carrello è pronto per i tuoi articoli.": "Your cart is ready for your items.", "Da confermare": "To be confirmed", "18H in Italia": "18H in Italy",
      "Nessun pagamento online richiesto in questa fase.": "No online payment is required at this stage.", "Nessun prodotto nel riepilogo.": "No products in the summary.", "Inserisci un codice sconto prima di applicarlo.": "Enter a discount code before applying it.", "Codice sconto inserito. Lo verificheremo alla conferma dell'ordine.": "Discount code entered. We will verify it when the order is confirmed.",
      "Apri assistente virtuale": "Open virtual assistant", "Chiudi assistente virtuale": "Close virtual assistant", "Assistente virtuale Haller Boutique": "Haller Boutique virtual assistant", "Assistente online": "Assistant online", "Prima di iniziare, lasciami i tuoi dati per seguirti meglio.": "Before we start, leave your details so I can assist you better.", "Cellulare": "Phone", "facoltativo": "optional", "I dati vengono usati solo per offrirti assistenza in questa conversazione.": "Your details are used only to assist you in this conversation.", "Inizia la chat": "Start chat", "Taglie": "Sizes", "Segui ordine": "Track order", "Scrivi qui...": "Type here...", "Invia messaggio": "Send message", "Un attimo, controllo.": "One moment, I'm checking.", "Non riesco a rispondere ora.": "I can't reply right now."
    },
    fr: {
      "Account | Haller Boutique": "Compte | Haller Boutique", "Account - Haller Boutique": "Compte - Haller Boutique", "Checkout | Haller Boutique": "Paiement | Haller Boutique", "Checkout - Haller Boutique": "Paiement - Haller Boutique", "Spedizioni | Haller Boutique": "Livraison | Haller Boutique", "Termini e condizioni | Haller Boutique": "Conditions generales | Haller Boutique", "Privacy Policy | Haller Boutique": "Confidentialite | Haller Boutique", "Admin | Haller Boutique": "Admin | Haller Boutique",
      "Tutti i diritti riservati.": "Tous droits reserves.", "Operazione in corso...": "Operation en cours...", "Operazione non riuscita.": "Echec de l'operation.", "Account creato.": "Compte cree.", "Accesso effettuato.": "Connexion reussie.", "Cliente": "Client", "Cellulare non inserito": "Telephone non renseigne",
      "Cambia lingua": "Changer de langue", "Menu account": "Menu du compte", "Accesso e registrazione": "Connexion et inscription", "Minimo 8 caratteri": "8 caracteres minimum", "© 2017 Haller Boutique. Tutti i diritti riservati.": "© 2017 Haller Boutique. Tous droits reserves.",
      "Menu checkout": "Menu de paiement", "Checkout ordine": "Paiement de la commande", "Città": "Ville", "Scegli metodo di pagamento": "Choisir un moyen de paiement", "Riepilogo ordine": "Recapitulatif de la commande", "Il carrello è pronto per i tuoi articoli.": "Votre panier est pret a recevoir vos articles.", "Da confermare": "A confirmer", "18H in Italia": "18H en Italie",
      "Nessun pagamento online richiesto in questa fase.": "Aucun paiement en ligne n'est requis a ce stade.", "Nessun prodotto nel riepilogo.": "Aucun produit dans le recapitulatif.", "Inserisci un codice sconto prima di applicarlo.": "Saisissez un code promotionnel avant de l'appliquer.", "Codice sconto inserito. Lo verificheremo alla conferma dell'ordine.": "Code promotionnel saisi. Il sera verifie lors de la confirmation.",
      "Cellulare": "Telephone", "facoltativo": "facultatif", "Taglie": "Tailles", "Segui ordine": "Suivre la commande", "Scrivi qui...": "Ecrivez ici...", "Invia messaggio": "Envoyer le message"
    },
    de: {
      "Account | Haller Boutique": "Konto | Haller Boutique", "Account - Haller Boutique": "Konto - Haller Boutique", "Checkout | Haller Boutique": "Kasse | Haller Boutique", "Checkout - Haller Boutique": "Kasse - Haller Boutique", "Spedizioni | Haller Boutique": "Versand | Haller Boutique", "Termini e condizioni | Haller Boutique": "Allgemeine Geschaftsbedingungen | Haller Boutique", "Privacy Policy | Haller Boutique": "Datenschutz | Haller Boutique", "Admin | Haller Boutique": "Admin | Haller Boutique",
      "Tutti i diritti riservati.": "Alle Rechte vorbehalten.", "Operazione in corso...": "Vorgang lauft...", "Operazione non riuscita.": "Vorgang fehlgeschlagen.", "Account creato.": "Konto erstellt.", "Accesso effettuato.": "Anmeldung erfolgreich.", "Cliente": "Kunde", "Cellulare non inserito": "Telefonnummer nicht angegeben",
      "Cambia lingua": "Sprache andern", "Menu account": "Kontomenu", "Accesso e registrazione": "Anmeldung und Registrierung", "Minimo 8 caratteri": "Mindestens 8 Zeichen", "© 2017 Haller Boutique. Tutti i diritti riservati.": "© 2017 Haller Boutique. Alle Rechte vorbehalten.",
      "Menu checkout": "Kassenmenu", "Checkout ordine": "Bestellung abschliessen", "Città": "Stadt", "Scegli metodo di pagamento": "Zahlungsart auswahlen", "Riepilogo ordine": "Bestellubersicht", "Il carrello è pronto per i tuoi articoli.": "Ihr Warenkorb ist bereit fur Ihre Artikel.", "Da confermare": "Noch zu bestatigen", "18H in Italia": "18H in Italien",
      "Nessun pagamento online richiesto in questa fase.": "In diesem Schritt ist keine Online-Zahlung erforderlich.", "Nessun prodotto nel riepilogo.": "Keine Produkte in der Zusammenfassung.", "Inserisci un codice sconto prima di applicarlo.": "Geben Sie vor dem Anwenden einen Rabattcode ein.", "Codice sconto inserito. Lo verificheremo alla conferma dell'ordine.": "Rabattcode eingegeben. Er wird bei der Bestatigung gepruft.",
      "Cellulare": "Telefon", "facoltativo": "optional", "Taglie": "Grossen", "Segui ordine": "Bestellung verfolgen", "Scrivi qui...": "Hier schreiben...", "Invia messaggio": "Nachricht senden"
    },
    es: {
      "Account | Haller Boutique": "Cuenta | Haller Boutique", "Account - Haller Boutique": "Cuenta - Haller Boutique", "Checkout | Haller Boutique": "Pago | Haller Boutique", "Checkout - Haller Boutique": "Pago - Haller Boutique", "Spedizioni | Haller Boutique": "Envios | Haller Boutique", "Termini e condizioni | Haller Boutique": "Terminos y condiciones | Haller Boutique", "Privacy Policy | Haller Boutique": "Privacidad | Haller Boutique", "Admin | Haller Boutique": "Admin | Haller Boutique",
      "Tutti i diritti riservati.": "Todos los derechos reservados.", "Operazione in corso...": "Operacion en curso...", "Operazione non riuscita.": "La operacion ha fallado.", "Account creato.": "Cuenta creada.", "Accesso effettuato.": "Sesion iniciada.", "Cliente": "Cliente", "Cellulare non inserito": "Telefono no indicado",
      "Cambia lingua": "Cambiar idioma", "Menu account": "Menu de cuenta", "Accesso e registrazione": "Inicio de sesion y registro", "Minimo 8 caratteri": "Minimo 8 caracteres", "© 2017 Haller Boutique. Tutti i diritti riservati.": "© 2017 Haller Boutique. Todos los derechos reservados.",
      "Menu checkout": "Menu de pago", "Checkout ordine": "Pago del pedido", "Città": "Ciudad", "Scegli metodo di pagamento": "Elige un metodo de pago", "Riepilogo ordine": "Resumen del pedido", "Il carrello è pronto per i tuoi articoli.": "Tu carrito esta listo para tus articulos.", "Da confermare": "Por confirmar", "18H in Italia": "18H en Italia",
      "Nessun pagamento online richiesto in questa fase.": "No se requiere pago en linea en esta fase.", "Nessun prodotto nel riepilogo.": "No hay productos en el resumen.", "Inserisci un codice sconto prima di applicarlo.": "Introduce un codigo de descuento antes de aplicarlo.", "Codice sconto inserito. Lo verificheremo alla conferma dell'ordine.": "Codigo de descuento introducido. Se verificara al confirmar el pedido.",
      "Cellulare": "Telefono", "facoltativo": "opcional", "Taglie": "Tallas", "Segui ordine": "Seguir pedido", "Scrivi qui...": "Escribe aqui...", "Invia messaggio": "Enviar mensaje"
    }
  };
  Object.entries(extraText).forEach(([code, values]) => Object.assign(text[code], values));

  const supportedLanguages = new Set(Object.keys(names));
  const changeLanguageLabels = { it: "Cambia lingua", en: "Change language", fr: "Changer de langue", de: "Sprache andern", es: "Cambiar idioma" };
  const originals = new WeakMap();
  const attributeOriginals = new WeakMap();
  const legalOriginals = new WeakMap();
  const legalPages = {
    en: {
      terms: `<p class="legal-eyebrow">Legal information</p><h1>Terms and conditions</h1><p>Last updated: 14 July 2026. These terms govern purchases made through Haller Boutique.</p><section class="legal-section"><h2>Orders and availability</h2><p>Submitting an order is a purchase offer. Order confirmation and shipping updates are sent to the contact details provided by the customer. Product availability is checked before fulfilment.</p></section><section class="legal-section"><h2>Prices and payments</h2><p>Prices and available payment methods are shown at checkout before the order is submitted. For cryptocurrency payments, use only the instructions and order code displayed during purchase.</p></section><section class="legal-section"><h2>Shipping and delivery</h2><p>Shipping information is available on the <a href="spedizioni.html">Shipping</a> page. The customer must verify the address entered at checkout and monitor the delivery status.</p></section><section class="legal-section"><h2>Replacements, withdrawal and refunds</h2><p>For after-sales support, Haller Boutique gives priority to replacing goods after checking the case and product availability. If goods are damaged, non-conforming or lost in transit, contact Aurora promptly with photos and the order code.</p><p>Refunds are assessed for these exceptional cases and where required by applicable law. This policy does not limit the 14-day right of withdrawal or statutory conformity guarantee where applicable.</p></section><section class="legal-section"><h2>Support</h2><p>For orders, replacements, deliveries and reports: <a href="index.html?chat=1">open Aurora chat</a>.</p></section>`,
      shipping: `<p class="legal-eyebrow">Purchase information</p><h1>Shipping</h1><p>Track your order using the code received in the purchase confirmation. For delivery support, always provide your order code.</p><section class="legal-section"><h2>Order preparation</h2><p>Orders are prepared after purchase details and product availability are checked. Support may contact the customer before shipping when information is incomplete.</p></section><section class="legal-section"><h2>Address and delivery</h2><p>The customer must provide a complete and accurate address. At delivery, check the external condition of the parcel before accepting it and report any issue promptly.</p></section><section class="legal-section"><h2>Lost or damaged order</h2><p>If a parcel is damaged or not delivered, contact Aurora with the order code, parcel photos and a short description. After verification, Haller Boutique prioritises replacement, without affecting rights under applicable law.</p></section><section class="legal-section"><h2>Shipping support</h2><p><a href="index.html?chat=1">Open Aurora chat</a></p></section>`,
      privacy: `<p class="legal-eyebrow">Personal data</p><h1>Privacy Policy</h1><p>Last updated: 14 July 2026. This notice describes the processing of personal data collected through Haller Boutique.</p><section class="legal-section"><h2>Data and purposes</h2><p>We may process identity, contact and delivery data, order information, support communications and technical browsing data to manage orders, shipping, customer support, security, abuse prevention and legal obligations.</p></section><section class="legal-section"><h2>Legal basis and retention</h2><p>Processing is necessary to perform a contract, meet legal duties and, where needed, for the legitimate interest in security and correct service operation. Data is retained only as long as necessary for these purposes and legal obligations.</p></section><section class="legal-section"><h2>Try-on photos</h2><p>Only when the user expressly authorises it, the uploaded photo and try-on preview are kept in a private archive accessible solely by store administration for support and recovery. Images are automatically deleted after 30 days.</p></section><section class="legal-section"><h2>Recipients and rights</h2><p>Data may be handled by providers supporting hosting, shipping, assistance, payments and security. We do not sell personal data. Where applicable, you may request access, correction, deletion, restriction, portability or object to processing.</p></section><section class="legal-section"><h2>Privacy contacts</h2><p>For requests about orders or personal data, contact <a href="index.html?chat=1">Aurora, Haller Boutique online assistant</a>.</p></section>`
    },
    fr: {
      terms: `<p class="legal-eyebrow">Informations legales</p><h1>Conditions generales</h1><p>Derniere mise a jour : 14 juillet 2026. Ces conditions regissent les achats effectues sur Haller Boutique.</p><section class="legal-section"><h2>Commandes et disponibilite</h2><p>L'envoi d'une commande constitue une proposition d'achat. La confirmation et les informations d'expedition sont envoyees aux coordonnees du client. La disponibilite est verifiee avant traitement.</p></section><section class="legal-section"><h2>Prix et paiements</h2><p>Les prix et moyens de paiement disponibles sont indiques au paiement. Pour les cryptomonnaies, utilisez uniquement les instructions et le numero de commande affiches.</p></section><section class="legal-section"><h2>Livraison, remplacement et remboursement</h2><p>Haller Boutique privilegie le remplacement apres verification. En cas de produit endommage, non conforme ou perdu, contactez rapidement Aurora avec photos et numero de commande. Les remboursements sont evalues dans ces cas exceptionnels et selon la loi applicable.</p></section><section class="legal-section"><h2>Assistance</h2><p><a href="index.html?chat=1">Ouvrir le chat Aurora</a></p></section>`,
      shipping: `<p class="legal-eyebrow">Informations achat</p><h1>Livraison</h1><p>Suivez la commande avec le code recu dans la confirmation. Pour toute assistance, indiquez toujours ce code.</p><section class="legal-section"><h2>Preparation</h2><p>Les commandes sont preparees apres verification des donnees et de la disponibilite. L'assistance peut contacter le client avant expedition en cas d'information incomplete.</p></section><section class="legal-section"><h2>Adresse et livraison</h2><p>Le client doit fournir une adresse complete et correcte. Verifiez l'etat exterieur du colis avant de l'accepter et signalez rapidement toute anomalie.</p></section><section class="legal-section"><h2>Colis perdu ou endommage</h2><p>Contactez Aurora avec le code commande, des photos et une breve description. Apres verification, Haller Boutique privilegie le remplacement, sans prejudice des droits legaux.</p></section>`,
      privacy: `<p class="legal-eyebrow">Donnees personnelles</p><h1>Politique de confidentialite</h1><p>Derniere mise a jour : 14 juillet 2026. Cette notice decrit le traitement des donnees collectees par Haller Boutique.</p><section class="legal-section"><h2>Donnees et finalites</h2><p>Nous pouvons traiter les donnees d'identite, de contact, de livraison, de commande, d'assistance et de navigation pour les commandes, livraisons, securite et obligations legales.</p></section><section class="legal-section"><h2>Base juridique et conservation</h2><p>Le traitement est necessaire au contrat, aux obligations legales et a la securite du service. Les donnees sont conservees pendant la duree necessaire.</p></section><section class="legal-section"><h2>Photos try-on</h2><p>Uniquement avec l'autorisation expresse de l'utilisateur, la photo et l'aperçu try-on sont conserves dans une archive privee accessible a l'administration pendant 30 jours maximum.</p></section><section class="legal-section"><h2>Contacts</h2><p>Pour les demandes relatives aux commandes ou aux donnees : <a href="index.html?chat=1">Aurora</a>.</p></section>`
    },
    de: {
      terms: `<p class="legal-eyebrow">Rechtliche Informationen</p><h1>Allgemeine Geschaftsbedingungen</h1><p>Letzte Aktualisierung: 14. Juli 2026. Diese Bedingungen gelten fur Einkaufe bei Haller Boutique.</p><section class="legal-section"><h2>Bestellungen und Verfugbarkeit</h2><p>Die Bestellung ist ein Kaufangebot. Bestatigung und Versandinformationen werden an die Kundendaten gesendet. Die Verfugbarkeit wird vor der Bearbeitung gepruft.</p></section><section class="legal-section"><h2>Preise und Zahlungen</h2><p>Preise und Zahlungsarten werden an der Kasse angezeigt. Fur Kryptowahrungen sind ausschliesslich die angezeigten Anweisungen und Bestellnummer zu verwenden.</p></section><section class="legal-section"><h2>Lieferung, Ersatz und Erstattung</h2><p>Haller Boutique bevorzugt nach Prufung einen Warenersatz. Bei beschadigter, nicht konformer oder verlorener Ware kontaktieren Sie Aurora mit Fotos und Bestellnummer. Erstattungen werden in Ausnahmefallen und nach geltendem Recht gepruft.</p></section><section class="legal-section"><h2>Support</h2><p><a href="index.html?chat=1">Aurora-Chat offnen</a></p></section>`,
      shipping: `<p class="legal-eyebrow">Kaufinformationen</p><h1>Versand</h1><p>Verfolgen Sie Ihre Bestellung mit dem Code aus der Kaufbestatigung. Geben Sie diesen Code bei Supportanfragen immer an.</p><section class="legal-section"><h2>Bestellvorbereitung</h2><p>Bestellungen werden nach Prufung der Angaben und Verfugbarkeit vorbereitet. Bei unvollstandigen Angaben kann der Support vor dem Versand Kontakt aufnehmen.</p></section><section class="legal-section"><h2>Adresse und Zustellung</h2><p>Der Kunde muss eine vollstandige korrekte Adresse angeben. Prufen Sie das Paket vor Annahme und melden Sie Auffalligkeiten umgehend.</p></section><section class="legal-section"><h2>Verlorenes oder beschadigtes Paket</h2><p>Kontaktieren Sie Aurora mit Bestellnummer, Fotos und kurzer Beschreibung. Nach Prufung wird ein Ersatz bevorzugt, unbeschadet gesetzlicher Rechte.</p></section>`,
      privacy: `<p class="legal-eyebrow">Personliche Daten</p><h1>Datenschutzerklarung</h1><p>Letzte Aktualisierung: 14. Juli 2026. Diese Information beschreibt die Verarbeitung personenbezogener Daten bei Haller Boutique.</p><section class="legal-section"><h2>Daten und Zwecke</h2><p>Wir konnen Identitats-, Kontakt-, Liefer-, Bestell-, Support- und technische Browsingdaten fur Bestellungen, Lieferungen, Sicherheit und gesetzliche Pflichten verarbeiten.</p></section><section class="legal-section"><h2>Rechtsgrundlage und Speicherung</h2><p>Die Verarbeitung dient Vertrag, gesetzlichen Pflichten und der Sicherheit des Dienstes. Daten werden nur so lange wie erforderlich gespeichert.</p></section><section class="legal-section"><h2>Try-on-Fotos</h2><p>Nur mit ausdrucklicher Zustimmung werden Foto und Vorschau bis zu 30 Tage in einem privaten Archiv der Shopverwaltung gespeichert.</p></section><section class="legal-section"><h2>Kontakt</h2><p>Bei Fragen zu Bestellungen oder Daten: <a href="index.html?chat=1">Aurora</a>.</p></section>`
    },
    es: {
      terms: `<p class="legal-eyebrow">Informacion legal</p><h1>Terminos y condiciones</h1><p>Ultima actualizacion: 14 de julio de 2026. Estas condiciones regulan las compras en Haller Boutique.</p><section class="legal-section"><h2>Pedidos y disponibilidad</h2><p>El envio de un pedido constituye una propuesta de compra. La confirmacion y la informacion de envio se envian a los datos del cliente. La disponibilidad se comprueba antes de la preparacion.</p></section><section class="legal-section"><h2>Precios y pagos</h2><p>Los precios y metodos de pago disponibles aparecen en el pago. Para criptomonedas usa solo las instrucciones y el codigo de pedido mostrados.</p></section><section class="legal-section"><h2>Entrega, sustitucion y reembolso</h2><p>Haller Boutique prioriza la sustitucion tras verificar el caso. Si la mercancia llega danada, no es conforme o se pierde, contacta pronto con Aurora con fotos y codigo de pedido. Los reembolsos se valoran en casos excepcionales y conforme a la ley.</p></section><section class="legal-section"><h2>Asistencia</h2><p><a href="index.html?chat=1">Abrir el chat Aurora</a></p></section>`,
      shipping: `<p class="legal-eyebrow">Informacion de compra</p><h1>Envios</h1><p>Sigue tu pedido con el codigo recibido en la confirmacion. Para asistencia de entrega indica siempre ese codigo.</p><section class="legal-section"><h2>Preparacion</h2><p>Los pedidos se preparan tras verificar datos y disponibilidad. El soporte puede contactar al cliente antes del envio si falta informacion.</p></section><section class="legal-section"><h2>Direccion y entrega</h2><p>El cliente debe indicar una direccion completa y correcta. Comprueba el estado exterior del paquete antes de aceptarlo e informa pronto de cualquier incidencia.</p></section><section class="legal-section"><h2>Pedido perdido o danado</h2><p>Contacta con Aurora con el codigo de pedido, fotos y una breve descripcion. Tras la verificacion, se prioriza la sustitucion sin limitar los derechos legales.</p></section>`,
      privacy: `<p class="legal-eyebrow">Datos personales</p><h1>Politica de privacidad</h1><p>Ultima actualizacion: 14 de julio de 2026. Esta informacion describe el tratamiento de datos personales en Haller Boutique.</p><section class="legal-section"><h2>Datos y finalidades</h2><p>Podemos tratar datos de identidad, contacto, entrega, pedidos, asistencia y navegacion para gestionar pedidos, envios, seguridad y obligaciones legales.</p></section><section class="legal-section"><h2>Base legal y conservacion</h2><p>El tratamiento es necesario para el contrato, obligaciones legales y seguridad del servicio. Los datos se conservan solo el tiempo necesario.</p></section><section class="legal-section"><h2>Fotos try-on</h2><p>Solo con autorizacion expresa se conservan la foto y vista previa durante un maximo de 30 dias en un archivo privado de administracion.</p></section><section class="legal-section"><h2>Contacto</h2><p>Para pedidos o datos personales: <a href="index.html?chat=1">Aurora</a>.</p></section>`
    }
  };
  const language = () => {
    const saved = localStorage.getItem(languageKey) || "it";
    return supportedLanguages.has(saved) ? saved : "it";
  };
  const translate = (value) => text[language()]?.[value] || value;
  const apply = () => {
    document.documentElement.lang = language();
    if (!document.documentElement.dataset.originalTitle) document.documentElement.dataset.originalTitle = document.title;
    document.title = translate(document.documentElement.dataset.originalTitle);
    const legalPage = document.querySelector("[data-legal-page]");
    if (legalPage) {
      if (!legalOriginals.has(legalPage)) legalOriginals.set(legalPage, legalPage.innerHTML);
      const legalHtml = language() === "it"
        ? legalOriginals.get(legalPage)
        : legalPages[language()]?.[legalPage.dataset.legalPage] || legalOriginals.get(legalPage);
      if (legalPage.innerHTML !== legalHtml) legalPage.innerHTML = legalHtml;
    }
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (!node.parentElement || ["SCRIPT", "STYLE"].includes(node.parentElement.tagName)) continue;
      if (node.parentElement.closest("[data-i18n], [data-i18n-html]")) continue;
      const original = originals.get(node) ?? node.nodeValue;
      originals.set(node, original);
      const trimmed = original.trim();
      if (!trimmed) continue;
      const value = translate(trimmed);
      const nextValue = value === trimmed ? original : original.replace(trimmed, value);
      if (node.nodeValue !== nextValue) node.nodeValue = nextValue;
    }
    document.querySelectorAll("[placeholder], [aria-label], [title]").forEach((element) => {
      if (element.matches(".language-toggle")) return;
      if (!attributeOriginals.has(element)) attributeOriginals.set(element, {});
      const saved = attributeOriginals.get(element);
      ["placeholder", "aria-label", "title"].forEach((attribute) => {
        if (!element.hasAttribute(attribute)) return;
        if (saved[attribute] === undefined) saved[attribute] = element.getAttribute(attribute);
        if (element.hasAttribute(`data-i18n-${attribute}`)) return;
        element.setAttribute(attribute, translate(saved[attribute]));
      });
    });
  };
  const bindPicker = (picker) => {
    if (picker.dataset.i18nBound === "true") return;
    const toggle = picker.querySelector(".language-toggle");
    const menu = picker.querySelector(".language-menu");
    const options = picker.querySelectorAll("[data-language-option]");
    if (!toggle || !menu) return;
    picker.dataset.i18nBound = "true";
    const refresh = () => {
      const current = language();
      options.forEach((option) => option.setAttribute("aria-checked", String(option.dataset.languageOption === current)));
      toggle.setAttribute("aria-label", `${changeLanguageLabels[current]}: ${names[current]}`);
    };
    refresh();
    toggle.addEventListener("click", () => {
      const open = menu.classList.toggle("is-open");
      toggle.setAttribute("aria-expanded", String(open));
    });
    options.forEach((option) => option.addEventListener("click", () => {
      localStorage.setItem(languageKey, option.dataset.languageOption);
      refresh();
      apply();
      window.dispatchEvent(new CustomEvent("haller-language-change", { detail: option.dataset.languageOption }));
      menu.classList.remove("is-open");
      toggle.setAttribute("aria-expanded", "false");
    }));
    document.addEventListener("click", (event) => {
      if (!picker.contains(event.target)) {
        menu.classList.remove("is-open");
        toggle.setAttribute("aria-expanded", "false");
      }
    });
  };
  window.HallerI18n = { apply, translate, language };
  const init = () => {
    apply();
    document.querySelectorAll("[data-language-picker]").forEach(bindPicker);
    const observer = new MutationObserver((mutations) => {
      if (mutations.some((mutation) => mutation.addedNodes.length > 0 || mutation.type === "characterData")) apply();
    });
    observer.observe(document.body, { childList: true, subtree: true });
  };
  if (document.body) init();
  else document.addEventListener("DOMContentLoaded", init, { once: true });
  window.addEventListener("haller-language-change", apply);
})();
